### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by nick-ez** [piatkowski/wckalkulator#6]
Hello. Thank you for your product!

branches/dev - 
If type Price Calculation select type Single-line formula, an error occurs when recalculating the price:
PHP Fatal error: Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, string given in /wc-kalkulator/src/FieldsetProduct.php on line 432

**Comment by piatkowski** [comment]
Thanks for information. It should check is_array before imploding.

**Comment by nick-ez** [comment]
Great, everything works!

Thank you!

Very good plugin. The best in this field!

Do you have alternative options for donation?

**Comment by piatkowski** [comment]
Thanks :) at this moment Paypal only
